project/collecteur/urls.py
from django.urls import path
from .views import *
app_name = 'collecteur'
urlpatterns = [
    path('',home,name='home'),
    path('collecteurs/',collecteurs,name='collecteurs'),
    path('vendeurs/',vendeurs,name='vendeurs'),
    path('commandes/',commandes,name='commandes'),
    path('delivered/<int:id>',delivered,name='delivered'),
    path('cancel/<int:id>',cancel,name='cancel'),
    path('history_commandes/',history_commandes,name='history_commandes'),
    path('products/',products,name='products'),
    path('addProd/',addProd,name='addProd'),
    path('update_produit/<int:id>',update_produit,name='update_produit'),
    path('delete_product/<int:id>',delete_product,name='delete_product'),
    path('AllCategories/',AllCategories,name='AllCategories'),
    path('addcategory/',addcategory,name='addcategory'),
    path('updatecategory/<int:id>',updatecategory,name='updatecategory'),
    path('deletecategory/<int:id>',deletecategory,name='deletecategory'),
    path('pick_command/<int:id>',pick_command,name='pick_command'),
]

project/main/urls.py
from django.urls import path
from .views import *
app_name = 'main'
urlpatterns = [
 
]

project/project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('users.urls')),
    path('collecteur/',include('collecteur.urls')),
    path('vendeur/',include('vendeur.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/vendeur/urls.py
from django.urls import path
from .views import *
app_name = 'vendeur'
urlpatterns = [
    path('categories/',categories,name='categories'),
    path('categories/<str:slug>',products,name='products'),
    path('details/<int:id>',details,name='details'),
    path('add/<int:id>',add,name='add'),
    path('poubelle/',poubelle,name='poubelle'),
    path('delete_from_poubelle/<int:id>',delete_from_poubelle,name='delete_from_poubelle'),
    path('sendCommand/',sendCommand,name='sendCommand'),

]

project/collecteur/models.py
from django.db import models
from decimal import Decimal
from django.utils.text import slugify

class Category(models.Model):
    title = models.CharField(max_length=100)
    banner = models.ImageField(upload_to='banner/cartegory', blank=True, null=True)
    slug = models.SlugField(unique=True,blank=True,null=True)  # Add a SlugField for the title slug

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        # Generate slug automatically from the title if not provided
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

class Product(models.Model):
    title = models.CharField(max_length=256)
    image = models.ImageField(upload_to='products/')
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    type = models.CharField(max_length=256)
    weight = models.DecimalField(max_digits=10, decimal_places=2)
    price_per_kilo = models.DecimalField(max_digits=10, decimal_places=2)
    desc = models.TextField()
    
    
    
    def __str__(self):
        return self.title

project/vendeur/models.py
from django.db import models
from users.models import User
from  collecteur.models import   *
# Create your models here.

class AllCommandes(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    celletuer = models.ForeignKey(User, on_delete=models.CASCADE, related_name='colletuer',blank=True,null=True)
    date_added = models.DateTimeField(auto_now_add=True , blank=True , null=True)
    commandes = models.ManyToManyField('VendeurCommande')
    totalPrice = models.DecimalField(decimal_places=2 , max_digits=20,null=True,blank=True)
    placed = models.BooleanField(default=False)
    selected = models.BooleanField(default=False)
    delivered = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True, null=True,blank=True)
    def __str__(self):
        return f'command de {self.user.username}'
    
class VendeurCommande(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,blank=True,null=True)
    produit = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(blank=True , null=True)
    price = models.DecimalField(decimal_places=2 , max_digits=20,null=True,blank=True)
    
    
    def __str__(self):
        return f"{self.produit}-{self.quantity}"

project/collecteur/views.py
from django.shortcuts import redirect, render
from django.core.mail import send_mail
from project.settings import EMAIL_HOST_USER
from .models import *
from .form import *
from users.models import *
from vendeur.models import *
from django.contrib.auth.decorators import login_required
# Create your views here.

@login_required(login_url="users:login")
def home(request):
    vendeurs = User.objects.filter(vendeur=True).order_by('-pk')[:5]
    collecteurs = User.objects.filter(collecteur=True).order_by('-pk')[:5]
    commandes_on_hold = AllCommandes.objects.filter(placed=True).order_by('-pk')[:5]
    commandes_collected = AllCommandes.objects.filter(delivered=True).order_by('-pk')[:5]
    vendeurs_count = User.objects.filter(vendeur=True).count()
    collecteur_count = User.objects.filter(collecteur=True).count()
    commandes_palced_count = AllCommandes.objects.filter(placed=True).count()
    commandes_collected_count = AllCommandes.objects.filter(delivered=True).count()
    context = {
        'commandes': commandes_on_hold,
        'commandes_collected': commandes_collected,
        'vendeurs': vendeurs,
        'collecteurs': collecteurs,
        'commandes_count': commandes_palced_count,
        'vendeurs_count': vendeurs_count,
        'collecteurs_count': collecteur_count,
        'commandes_collected_count': commandes_collected_count,
    }
    return render(request, 'collecteur/home.html', context)

@login_required(login_url="users:login")
def collecteurs(request):
    collecteur = User.objects.filter(collecteur=True)
    context = {
        'collecteurs': collecteur
    }
    return render(request, 'collecteur/collecteurs.html', context)

@login_required(login_url="users:login")
def vendeurs(request):
    vendeur = User.objects.filter(vendeur=True)
    context = {
        'vendeur': vendeur
    }
    return render(request, 'collecteur/vendeurs.html', context)


@login_required(login_url="users:login")
def commandes(request):
    commande = AllCommandes.objects.filter(placed=True, delivered=False)

    context = {
        'commande': commande
    }
    return render(request, 'collecteur/commande.html', context)

@login_required(login_url="users:login")
def pick_command(request,id):
    commande = AllCommandes.objects.get(pk=id)
    collacter = request.user
    commande.selected = True
    commande.celletuer = collacter
    commande.save()
    # ////////////////////////////////////////////////////
    subject = 'Commande Pick Up'
    message = f'Bonjour {commande.user}, \nLa Commande N°{commande.id} a été sélectionnée par {collacter} pour être ramassé'
    email = commande.user.email
    revicer = [email]
    send_mail(
        subject,
        message,
        EMAIL_HOST_USER,
        revicer,
        fail_silently=False,
    )
    # ////////////////////////////////////////////////////
    return redirect('collecteur:commandes')


@login_required(login_url="users:login")
def cancel(request,id):
    commande = AllCommandes.objects.get(pk=id)
    collacter = None
    commande.selected = False
    commande.celletuer = collacter
     # ////////////////////////////////////////////////////
    subject = 'Commande annule'
    message = f'Bonjour {commande.user}, \nLa Commande N°{commande.id} a été annule par {collacter} pour être ramassé'
    email = commande.user.email
    revicer = [email]
    send_mail(
        subject,
        message,
        EMAIL_HOST_USER,
        revicer,
        fail_silently=False,
    )
    # ////////////////////////////////////////////////////
    commande.save()
    return redirect('collecteur:commandes')

@login_required(login_url="users:login")
def delivered(request,id):
    commande = AllCommandes.objects.get(pk=id)
    commande.delivered = True
     # ////////////////////////////////////////////////////
    subject = 'Commande Pick Up'
    message = f'Bonjour {commande.user}, \nLa Commande N°{commande.id} a été recupere par {commande.celletuer} '
    email = commande.user.email
    revicer = [email]
    send_mail(
        subject,
        message,
        EMAIL_HOST_USER,
        revicer,
        fail_silently=False,
    )
    # ////////////////////////////////////////////////////
    commande.save()
    return redirect('collecteur:commandes')

@login_required(login_url="users:login")
def history_commandes(request):
    commande = AllCommandes.objects.filter(delivered=True)
    context = {
        'commande': commande
    }
    return render(request, 'collecteur/old_command.html', context)

@login_required(login_url="users:login")
def products(request):
    products = Product.objects.all()
    context = {
        'products': products
    }
    return render(request, 'collecteur/products.html', context)

@login_required(login_url="users:login")
def addProd(request):
    form = addproduit()

    if request.method == 'POST':
        form = addproduit(request.POST, request.FILES)
        if form.is_valid():

            sv = form.save(commit=False)
            sv.totalPrice = sv.weight * sv.price_per_kilo
            sv.save()
            return redirect('collecteur:products')

    context = {
        'form': form
    }
    return render(request, 'collecteur/add_products.html', context)

@login_required(login_url="users:login")
def update_produit(request, id):
    product = Product.objects.get(id=id)

    if request.method == 'POST':
        form = Updateproduit(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return redirect('collecteur:products')
    else:
        form = Updateproduit(instance=product)
    context = {
        'form': form
    }
    return render(request, 'collecteur/add_products.html', context)

@login_required(login_url="users:login")
def delete_product(request, id):
    product = Product.objects.get(id=id)
    product.delete()
    return redirect('collecteur:products')

@login_required(login_url="users:login")
def AllCategories(request):
    category = Category.objects.all()
    print('__________________________')
    print(category)
    context = {
        'category': category
    }
    return render(request, 'collecteur/category.html', context)

@login_required(login_url="users:login")
def addcategory(request):
    form = addCategory()
    if request.method == "POST":
        form = addCategory(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('collecteur:AllCategories')
    context = {
        'form': form
    }
    return render(request, 'collecteur/add_category.html', context)

@login_required(login_url="users:login")
def updatecategory(request, id):
    category = Category.objects.get(pk=id)

    if request.method == "POST":
        form = UpdateCategory(request.POST, request.FILES, instance=category)
        if form.is_valid():
            form.save()
            return redirect('collecteur:AllCategories')
    else:
        form = UpdateCategory(instance=category)

    context = {
        'form': form
    }
    return render(request, 'collecteur/add_category.html', context)

@login_required(login_url="users:login")
def deletecategory(request, id):
    category = Category.objects.get(pk=id)
    category.delete()
    return redirect('collecteur:AllCategories')

project/vendeur/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.core.exceptions import ObjectDoesNotExist
from collecteur.models import *
from .models import *
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError


# Create your views here.
@login_required(login_url="users:login")
def categories(request):
    all_categories = Category.objects.all()
   
    context = {
        'all_categories': all_categories
    }
    return render(request, 'vendeur/categories.html', context)

@login_required(login_url="users:login")
def products(request,slug):
    category_needed = Category.objects.get(slug=slug)
    category_id = category_needed.pk
    products = Product.objects.filter(category=category_id)  
    print('____________________________')
    print(products)

    

    context = {
        'products' :products
    }
    return render(request,'vendeur/products.html',context)

@login_required(login_url="users:login")
def details(request, id): 
    product = Product.objects.get(pk=id)
    context = {
        'product': product
    }
    return render(request, 'vendeur/details.html', context)



@login_required(login_url="users:login")
def add(request, id):
    current_url = request.build_absolute_uri()
    print("Current URL:", current_url)
    
    if request.method == "POST":
        product = Product.objects.get(id=id)
        quantity = int(request.POST['quantity'])  # Convert quantity to an integer
        print(quantity)
        price = Decimal(quantity) * product.price_per_kilo  # Calculate total price
        
        # Get or create AllCommandes object for the current user
        mycommands, created = AllCommandes.objects.get_or_create(
            user=request.user
        )
        
    
        # Create or get the VendeurCommande object for the current user and product
        command, created = VendeurCommande.objects.get_or_create(
            produit=product,
            user=request.user,
            defaults={'quantity': 0}  # Default quantity is 0
        )
        
        # Update the quantity and price of the VendeurCommande object
        command.quantity += quantity
        command.price = price
        
        try:
            command.save()
        except IntegrityError:
            # Handle the case if saving the command fails due to IntegrityError
            # For example, if there's a unique constraint violation
            pass
        
        # Add the VendeurCommande object to the user's AllCommandes
        mycommands.commandes.add(command)
        
        # Update the total price of the AllCommandes object
        mycommands.totalPrice = sum(cmd.price for cmd in mycommands.commandes.all())
        mycommands.save()
    
    return redirect('vendeur:details', id=id)

@login_required(login_url="users:login")
def poubelle(request):
    poubelle = AllCommandes.objects.get(user=request.user)
    poubelle =poubelle.commandes.all()
    items = []
    for  item in poubelle:
        items.append(item)
    
    print(items)
    context = {
        'poubelle': poubelle,
        'items': items
    }
    return render(request, 'vendeur/poubelle.html', context)

@login_required(login_url="users:login")
def deletefrompoubelle(request,id):
    command = VendeurCommande.objects.filter(pk=id , user=request.user)
    command.commandes.remove(command)

@login_required(login_url="users:login")
def delete_from_poubelle(request, id):
    # Fetch the command object
    command = get_object_or_404(VendeurCommande, pk=id, user=request.user)
    
    # Remove the command from the commandes Many-to-Many field
    command.allcommandes_set.clear()  # Assuming allcommandes_set is the related name
    command.delete()
    return redirect('vendeur:poubelle')


@login_required(login_url="users:login")    
def sendCommand(resqust):
    command = AllCommandes.objects.get(user=resqust.user)
    if not command.placed:
        command.placed = True
        command.save()
    
    return redirect('vendeur:categories')

project/templates/collecteur/category.html
{% extends "base.html" %}

{% block title %}
  Categories
{% endblock title %}

{% block content %}
<div class="page-header">
  <div class="row align-items-center">
    <div class="col">
      <h3 class="page-title">Categories</h3>
      <ul class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="{% url 'collecteur:home' %}">Dashboard</a>
        </li>
        <li class="breadcrumb-item active">Categories</li>
      </ul>
    </div>
    <div class="col-auto text-right float-right ml-auto">
      <a href="{% url 'collecteur:addcategory'  %}" class="btn btn-outline-primary mr-2"
        ></i> add new Category</a
      >
      
    </div>
  </div>
</div>
<div class="row">
  <div class="col-sm-12">
    <div class="card card-table">
      <div class="card-body">
        <div class="table-responsive">
          <table
   id="table_id"
     class="table table-hover table-center mb-0 "
   > 
            <thead>
              <tr>
                <th>category ID</th>
                <th>category Name</th>

                <th class="text-right">Action</th>
              </tr>
            </thead>
            <tbody>

              {% for cate in category %}
              <tr>
                <td>{{cate.id}}</td>
                <td>
                  <h2>
                    <a>{{cate.title}}</a>
                  </h2>
                </td>
              
                <td class="text-right">
                  <div class="actions">
                    <a
                      href="{% url 'collecteur:updatecategory' cate.id %}"
                      class="btn btn-sm bg-success-light mr-2"
                    >
                      <i class="fas fa-pen"></i>
                    </a>
                    <a href="{% url 'collecteur:deletecategory' cate.id %}" class="btn btn-sm bg-danger-light">
                      <i class="fas fa-trash"></i>
                    </a>
                  </div>
                </td>
              </tr>
                
              {% endfor %}

            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

project/templates/collecteur/commande.html
{% extends "base.html" %}

{% block title %}
  collecteurs
{% endblock title %}

{% block content %}
<div class="page-header">
  <div class="row align-items-center">
    <div class="col">
      <h3 class="page-title">collecteurs</h3>
      <ul class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="{% url 'collecteur:home' %}">Dashboard</a>
        </li>
        <li class="breadcrumb-item active">collecteurs</li>
      </ul>
    </div>
    <div class="col-auto text-right float-right ml-auto">
      <a href="{% url 'add_collectuer' %}" class="btn btn-outline-primary mr-2"
        ></i> add new collecteur</a
      >
      
    </div>
  </div>
</div>
<div class="row">
  <div class="col-sm-12">
    <div class="card card-table">
      <div class="card-body">
        <div class="table-responsive">
          <table
   id="table_id"
     class="table table-hover table-center mb-0 "
   > 
            <thead>
              <tr>
                <th>ID</th>
                <th>Date</th>
                <th>Vendeur</th>
                <th>Status</th>
                <th>Selected By</th>

                <th class="text-right">Action</th>
              </tr>
            </thead>
            <tbody>

              {% for cmd in commande %}
              <tr>
                <td>{{cmd.id}}</td>
                <td>
                  <h2>
                    <a>{{cmd.created_date}}</a>
                  </h2>
                </td>
                <td>{{cmd.user.first_name}} {{cmd.user.last_name}}  <br> {{cmd.user.phone}} </td>
                <td>
                  {% if cmd.selected %}
                  entrain de collecter
                  {% else %}
                  en attente
                  {% endif %}  
                </td>
                <td>
                  {% if cmd.selected %}
                    
                    <span class="badge badge-danger">{{cmd.celletuer.username}}</span>
                    {% else %}
                    <span class="badge badge-success">Not Selected yet</span>
                    
                  {% endif %}
                </td>
                <td class="text-right">
                  {% if cmd.selected and cmd.celletuer == user %}
                  <div class="actions">
                    <a
                      href="{% url 'collecteur:cancel' cmd.id %}"
                      class="btn btn-danger btn-sm"
                    >
                    Cancel
                    </a>
                    <a href="{% url 'collecteur:delivered' cmd.id %}" class="btn btn-success btn-sm">
                      delivered
                    </a>
                  </div>
                  {% elif cmd.selected %}
                  <div class="actions">
                    <a
                      href="{% url 'block' cmd.id  %}"
                      class="btn btn-sm bg-success-light mr-2"
                    >
                    <i class="fas fa-user-alt-slash"></i>
                    </a>
                    <a href="{% url 'delete' cmd.id  %}" class="btn btn-sm bg-danger-light">
                      <i class="fas fa-trash"></i>
                    </a>
                  </div>
                  {% else %}
                    <a href="{% url 'collecteur:pick_command' cmd.id %}">pick</a> 
                    {% endif %}
                </td>
              </tr>
                
              {% endfor %}

            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

project/templates/collecteur/old__command.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
    
    <link rel="stylesheet" href="{% static 'CSS/home2.css' %}">
    <link rel="stylesheet" href="{% static 'CSS/table.css' %}">

</head>
<body>
  <div class="contaner">
    <div class="home2">
      <div class="logo">
        <img src="../my photo/LOGOO.jpg" alt="logo" />
      </div>
      <ul>
        <li>
          <a href="{% url 'collecteur:home' %}" >
            <span>dashbord</span>
          </a>
        </li>
        <li>
            <a href="{% url 'collecteur:AllCategories' %}" >
              <span>categories</span>
            </a>
        </li>
        <li>
            <a href="{% url 'collecteur:products' %}" >
              <span>products</span>
            </a>
        </li>
        <li>
            <a href="{% url 'collecteur:collecteurs' %}" >
              <span>collecteur</span>
            </a>
        </li>
        <li>
          <a href="{% url 'collecteur:vendeurs' %}" >
            <span>vendeur</span>
          </a>
        </li>
        <li>
          <a href="{% url 'collecteur:commandes' %}" >
            <span>command</span>
          </a>
        </li>
        <li>
          <a href="{% url 'collecteur:history_commandes' %}" >
            <span>historique des command</span>
          </a>
        </li>
        <li>
          <a href="{% url 'users:logout' %}">
            <span>Logout</span>
          </a>
        </li>
      </ul>
    </div>
  </div>
      <div class="content" >
        <h1>List of command</h1>
        <table >
            <thead>
            <tr>
                <td>command_id</td>
                <td>command_date</td>
                <td>vendeur</td>
                <td>command_etat</td>
                <td>collecteur_id</td>          
              </tr>
          </thead>
          <tbody>
            {% for cmd in commande %}
              
              <tr>
                  <td>{{cmd.id}}</td>
                  <td>{{cmd.created_date}} {{cmd.last_name}}</td>
                  <td>{{cmd.user.first_name}} {{cmd.user.last_name}}  <br> {{cmd.user.phone}} </td>
                  <td>
                    collected 
                  </td>
                  <td>
                      {% if cmd.selected %}
                      {{cmd.celletuer.username}}
                      {% else %}
                      not have been selected by any collectuer
                      
                    {% endif %}
                  </td>

              </tr>
              {% endfor %}

              <!-- Add more rows as needed -->
          </tbody>

        </table >
        </div>
     
  
     
</body>
</html>

project/templates/collecteur/old_old_commande.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
    
    <link rel="stylesheet" href="{% static 'CSS/home2.css' %}">
    <link rel="stylesheet" href="{% static 'CSS/table.css' %}">

</head>
<body>
  <div class="contaner">
    <div class="home2">
      <div class="logo">
        <img src="../my photo/LOGOO.jpg" alt="logo" />
      </div>
      <ul>
        <li>
          <a href="{% url 'collecteur:home' %}" >
            <span>dashbord</span>
          </a>
        </li>
        <li>
            <a href="{% url 'collecteur:AllCategories' %}" >
              <span>categories</span>
            </a>
        </li>
        <li>
            <a href="{% url 'collecteur:products' %}" >
              <span>products</span>
            </a>
        </li>
        <li>
            <a href="{% url 'collecteur:collecteurs' %}" >
              <span>collecteur</span>
            </a>
        </li>
        <li>
          <a href="{% url 'collecteur:vendeurs' %}" >
            <span>vendeur</span>
          </a>
        </li>
        <li>
          <a href="{% url 'collecteur:commandes' %}" >
            <span>command</span>
          </a>
        </li>
        <li>
          <a href="{% url 'collecteur:history_commandes' %}" >
            <span>historique des command</span>
          </a>
        </li>
        <li>
          <a href="{% url 'users:logout' %}">
            <span>Logout</span>
          </a>
        </li>
      </ul>
    </div>
  </div>
      <div class="content" >
        <h1>List of command</h1>
        <table >
            <thead>
            <tr>
                <td>command_id</td>
                <td>command_date</td>
                <td>vendeur</td>
                <td>command_etat</td>
                <td>collecteur_id</td>          
                <th>action</th>
              </tr>
          </thead>
          <tbody>
            {% for cmd in commande %}
              
              <tr>
                  <td>{{cmd.id}}</td>
                  <td>{{cmd.created_date}} {{cmd.last_name}}</td>
                  <td>{{cmd.user.first_name}} {{cmd.user.last_name}}  <br> {{cmd.user.phone}} </td>
                  <td>
                  
                    {% if cmd.selected %}
                    entrain de collecter
                    {% else %}
                    en attente
                    {% endif %}  
                  </td>
                  <td>
                    {% if cmd.selected %}
                    {{cmd.celletuer.username}}
                    {% else %}
                    not have been selected by any collectuer
                    
                  {% endif %}
                  </td>
                  <td>
                    {% if cmd.selected and cmd.celletuer == user %}
                    <a href="{% url 'collecteur:cancel' cmd.id %}">annule</a> 
                    <a href="{% url 'collecteur:delivered' cmd.id %}">delivered</a> 
                    
                    {% elif cmd.selected %}
                    <button disabled> collected</button>
                    
                    {% else %}
                    <a href="{% url 'collecteur:pick_command' cmd.id %}">pick</a> 
                    {% endif %}
                  </td>
              </tr>
              {% endfor %}

              <!-- Add more rows as needed -->
          </tbody>

        </table >
        </div>
     
  
     
</body>
</html>

project/templates/collecteur/old_products.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
    
    <link rel="stylesheet" href="{% static 'CSS/home2.css' %}">
    <link rel="stylesheet" href="{% static 'CSS/table.css' %}">

</head>
<body>
  <div class="contaner">
    <div class="home2">
      <div class="logo">
        <img src="../my photo/LOGOO.jpg" alt="logo" />
      </div>
      <ul>
        <li>
          <a href="{% url 'collecteur:home' %}" >
            <span>dashbord</span>
          </a>
        </li>
        <li>
            <a href="{% url 'collecteur:AllCategories' %}" >
              <span>categories</span>
            </a>
        </li>
        <li>
            <a href="{% url 'collecteur:products' %}" >
              <span>products</span>
            </a>
        </li>
        <li>
            <a href="{% url 'collecteur:collecteurs' %}" >
              <span>collecteur</span>
            </a>
        </li>
        <li>
          <a href="{% url 'collecteur:vendeurs' %}" >
            <span>vendeur</span>
          </a>
        </li>
        <li>
          <a href="{% url 'collecteur:commandes' %}" >
            <span>command</span>
          </a>
        </li>
        <li>
          <a href="{% url 'collecteur:history_commandes' %}" >
            <span>historique des command</span>
          </a>
        </li>
        <li>
          <a href="{% url 'users:logout' %}">
            <span>Logout</span>
          </a>
        </li>
      </ul>
    </div>
  </div>
    <div class="content">
        <h1>List des products</h1>
        <table>
            <thead>
                <tr>
                    <th>Collecteur ID</th>
                    <th>nom de products</th>
                    <th>category de products</th>

                    <th>type</th>
                    <th>prix</th>
                    <th>action</th>
                </tr>
            </thead>
            <tbody>
              <tr>
                  <td>------------------</td>
                  <td>------------------</td>
                  <td>------------------</td>
                  <td>------------------</td>
                  <td>------------------</td>

                  <td>
                    <a href="{% url 'collecteur:addProd' %}">ajoute</a> 
                  </td>
              </tr>
              {% for product in products %}
                
                <tr>
                    <td>{{product.id}}</td>
                    <td>{{product.title}}</td>
                    <td>{{product.category}}</td>
                    <td>{{product.type}}</td>
                    <td>{{product.price_per_kilo}}</td>

                    <td>
                      <a href="{% url 'collecteur:update_produit' product.id %}">update</a> 
                      <a href="{% url 'collecteur:delete_product' product.id %}">delete</a>
                    </td>
                </tr>
                {% endfor %}
 
                <!-- Add more rows as needed -->
            </tbody>
        </table>
    </div>
</body>
</html>