project/main/urls.py
from django.urls import path
from .views import *
app_name = 'main'
urlpatterns = [
 
]

project/project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('users.urls')),
    path('collecteur/',include('collecteur.urls')),
    path('vendeur/',include('vendeur.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/vendeur/urls.py
from django.urls import path
from .views import *
app_name = 'vendeur'
urlpatterns = [
    path('categories/',categories,name='categories'),
    path('categories/<str:slug>',products,name='products'),
    path('details/<int:id>',details,name='details'),
    path('add/<int:id>',add,name='add'),
    path('poubelle/',poubelle,name='poubelle'),
    path('delete_from_poubelle/<int:id>',delete_from_poubelle,name='delete_from_poubelle'),
    path('sendCommand/',sendCommand,name='sendCommand'),

]

project/vendeur/models.py
from django.db import models
from users.models import User
from  collecteur.models import   *
# Create your models here.

class AllCommandes(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    celletuer = models.ForeignKey(User, on_delete=models.CASCADE, related_name='colletuer',blank=True,null=True)
    date_added = models.DateTimeField(auto_now_add=True , blank=True , null=True)
    commandes = models.ManyToManyField('VendeurCommande')
    totalPrice = models.DecimalField(decimal_places=2 , max_digits=20,null=True,blank=True)
    placed = models.BooleanField(default=False)
    selected = models.BooleanField(default=False)
    delivered = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True, null=True,blank=True)
    def __str__(self):
        return f'command de {self.user.username}'
    
class VendeurCommande(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,blank=True,null=True)
    produit = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(blank=True , null=True)
    price = models.DecimalField(decimal_places=2 , max_digits=20,null=True,blank=True)
    
    
    def __str__(self):
        return f"{self.produit}-{self.quantity}"

project/vendeur/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.core.exceptions import ObjectDoesNotExist
from collecteur.models import *
from .models import *
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError


# Create your views here.
@login_required(login_url="users:login")
def categories(request):
    all_categories = Category.objects.all()
   
    context = {
        'all_categories': all_categories
    }
    return render(request, 'vendeur/categories.html', context)

@login_required(login_url="users:login")
def products(request,slug):
    category_needed = Category.objects.get(slug=slug)
    category_id = category_needed.pk
    products = Product.objects.filter(category=category_id)  
    print('____________________________')
    print(products)

    

    context = {
        'products' :products
    }
    return render(request,'vendeur/products.html',context)

@login_required(login_url="users:login")
def details(request, id): 
    product = Product.objects.get(pk=id)
    context = {
        'product': product
    }
    return render(request, 'vendeur/details.html', context)



@login_required(login_url="users:login")
def add(request, id):
    current_url = request.build_absolute_uri()
    print("Current URL:", current_url)
    
    if request.method == "POST":
        product = Product.objects.get(id=id)
        quantity = int(request.POST['quantity'])  # Convert quantity to an integer
        print(quantity)
        price = Decimal(quantity) * product.price_per_kilo  # Calculate total price
        
        # Get or create AllCommandes object for the current user
        mycommands, created = AllCommandes.objects.get_or_create(
            user=request.user
        )
        
    
        # Create or get the VendeurCommande object for the current user and product
        command, created = VendeurCommande.objects.get_or_create(
            produit=product,
            user=request.user,
            defaults={'quantity': 0}  # Default quantity is 0
        )
        
        # Update the quantity and price of the VendeurCommande object
        command.quantity += quantity
        command.price = price
        
        try:
            command.save()
        except IntegrityError:
            # Handle the case if saving the command fails due to IntegrityError
            # For example, if there's a unique constraint violation
            pass
        
        # Add the VendeurCommande object to the user's AllCommandes
        mycommands.commandes.add(command)
        
        # Update the total price of the AllCommandes object
        mycommands.totalPrice = sum(cmd.price for cmd in mycommands.commandes.all())
        mycommands.save()
    
    return redirect('vendeur:details', id=id)

@login_required(login_url="users:login")
def poubelle(request):
    poubelle = AllCommandes.objects.get(user=request.user)
    poubelle =poubelle.commandes.all()
    items = []
    for  item in poubelle:
        items.append(item)
    
    print(items)
    context = {
        'poubelle': poubelle,
        'items': items
    }
    return render(request, 'vendeur/poubelle.html', context)

@login_required(login_url="users:login")
def deletefrompoubelle(request,id):
    command = VendeurCommande.objects.filter(pk=id , user=request.user)
    command.commandes.remove(command)

@login_required(login_url="users:login")
def delete_from_poubelle(request, id):
    # Fetch the command object
    command = get_object_or_404(VendeurCommande, pk=id, user=request.user)
    
    # Remove the command from the commandes Many-to-Many field
    command.allcommandes_set.clear()  # Assuming allcommandes_set is the related name
    command.delete()
    return redirect('vendeur:poubelle')


@login_required(login_url="users:login")    
def sendCommand(resqust):
    command = AllCommandes.objects.get(user=resqust.user)
    if not command.placed:
        command.placed = True
        command.save()
    
    return redirect('vendeur:categories')

project/templates/vendeur/categories.html
{% extends "base.html" %} 
{% load static %} 
{% block title %} categories {% endblock title %} 
{% block content %}
<div class="comp-sec-wrapper">
  <section class="comp-section comp-cards">
    <div class="section-header">
      <h4 class="section-title">Categories</h4>
      <div class="line"></div>
    </div>
    <div class="row">
      {% for category in all_categories %}
      <div class="col-12 col-md-6 col-lg-4 d-flex">
        <div class="card flex-fill">
          {% if category.banner %}
          <img
            alt="Card Image"
            src="{{category.banner.url}}"
            class="card-img-top"
          />

          {% else %}
          <img
            alt="Card Image"
            src="{% static 'img/No_Image_Available.jpg' %}"
            class="card-img-top"
          />

          {% endif %}
          <div class="card-header">
            <h5 class="card-title mb-0">{{category.title}}</h5>
          </div>
          <div class="card-body">
            <a
              class="btn btn-primary"
              href="{% url 'vendeur:products' category.slug   %}"
              >details</a
            >
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </section>
</div>
{% endblock content %}

project/templates/vendeur/details.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  {{product.title}}
{% endblock title %}
{% block content %}
<style class="cp-pen-styles">

    
    .ctrl {
      -webkit-box-flex: 0;
      -webkit-flex: 0 0 auto;
      -ms-flex: 0 0 auto;
      flex: 0 0 auto;
      display: -webkit-box;
      display: -webkit-flex;
      display: -ms-flexbox;
      display: flex;
      -webkit-box-align: center;
      -webkit-align-items: center;
      -ms-flex-align: center;
      align-items: center;
      border-bottom: 1px solid #D5DCE6;
      background-color: #fff;
      border-radius: 5px;
      font-size: 30px;
    }
    
    .ctrl__counter {
      position: relative;
      width: 50px;
      height: 100px;
      color: #333C48;
      text-align: center;
      overflow: hidden;
    }
    
    .ctrl__counter.is-input .ctrl__counter-num {
      visability: hidden;
      opacity: 0;
      -webkit-transition: opacity 100ms ease-in;
      transition: opacity 100ms ease-in;
    }
    
    .ctrl__counter.is-input .ctrl__counter-input {
      visability: visible;
      opacity: 1;
      -webkit-transition: opacity 100ms ease-in;
      transition: opacity 100ms ease-in;
    }
    
    .ctrl__counter-input {
      width: 100%;
      margin: 0;
      padding: 0;
      position: relative;
      z-index: 2;
      box-shadow: none;
      outline: none;
      border: none;
      color: #333C48;
      font-size: 30px;
      line-height: 100px;
      text-align: center;
      visability: hidden;
      opacity: 0;
      -webkit-transition: opacity 100ms ease-in;
      transition: opacity 100ms ease-in;
    }
    
    .ctrl__counter-num {
      position: absolute;
      z-index: 1;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
      line-height: 100px;
      visability: visible;
      opacity: 1;
      -webkit-transition: opacity 100ms ease-in;
      transition: opacity 100ms ease-in;
    }
    
    .ctrl__counter-num.is-increment-hide {
      opacity: 0;
      -webkit-transform: translateY(-50px);
      transform: translateY(-50px);
      -webkit-animation: increment-prev 100ms ease-in;
      animation: increment-prev 100ms ease-in;
    }
    
    .ctrl__counter-num.is-increment-visible {
      opacity: 1;
      -webkit-transform: translateY(0);
      transform: translateY(0);
      -webkit-animation: increment-next 100ms ease-out;
      animation: increment-next 100ms ease-out;
    }
    
    .ctrl__counter-num.is-decrement-hide {
      opacity: 0;
      -webkit-transform: translateY(50px);
      transform: translateY(50px);
      -webkit-animation: decrement-prev 100ms ease-in;
      animation: decrement-prev 100ms ease-in;
    }
    
    .ctrl__counter-num.is-decrement-visible {
      opacity: 1;
      -webkit-transform: translateY(0);
      transform: translateY(0);
      -webkit-animation: decrement-next 100ms ease-out;
      animation: decrement-next 100ms ease-out;
    }
    
    .ctrl__button {
      width: 50px;
      line-height: 50px;
      text-align: center;
      color: #fff;
      cursor: pointer;
      background-color: #8498a7;
      -webkit-transition: background-color 100ms ease-in;
      transition: background-color 100ms ease-in;
    }
    
    .ctrl__button:hover {
      background-color: #90a2b0;
      -webkit-transition: background-color 100ms ease-in;
      transition: background-color 100ms ease-in;
    }
    
    .ctrl__button:active {
      background-color: #778996;
      -webkit-transition: background-color 100ms ease-in;
      transition: background-color 100ms ease-in;
    }
    
    .ctrl__button--decrement { border-radius: 5px 0 0 5px; }
    
    .ctrl__button--increment { border-radius: 0 5px 5px 0; }
     @-webkit-keyframes 
    decrement-prev {  from {
     opacity: 1;
     -webkit-transform: translateY(0);
     transform: translateY(0);
    }
    }
     @keyframes 
    decrement-prev {  from {
     opacity: 1;
     -webkit-transform: translateY(0);
     transform: translateY(0);
    }
    }
    @-webkit-keyframes 
    decrement-next {  from {
     opacity: 0;
     -webkit-transform: translateY(-50px);
     transform: translateY(-50px);
    }
    }
    @keyframes 
    decrement-next {  from {
     opacity: 0;
     -webkit-transform: translateY(-50px);
     transform: translateY(-50px);
    }
    }
    @-webkit-keyframes 
    increment-prev {  from {
     opacity: 1;
     -webkit-transform: translateY(0);
     transform: translateY(0);
    }
    }
    @keyframes 
    increment-prev {  from {
     opacity: 1;
     -webkit-transform: translateY(0);
     transform: translateY(0);
    }
    }
    @-webkit-keyframes 
    increment-next {  from {
     opacity: 0;
     -webkit-transform: translateY(50px);
     transform: translateY(50px);
    }
    }
    @keyframes 
    increment-next {  from {
     opacity: 0;
     -webkit-transform: translateY(50px);
     transform: translateY(50px);
    }
    }
    </style>

          <div class="page-header">
            <div class="row">
              <div class="col-sm-12">
                <h3 class="page-title">Product Details</h3>
                <ul class="breadcrumb">
                  <li class="breadcrumb-item">
                    <a href="teachers.html">Products</a>
                  </li>
                  <li class="breadcrumb-item active">product Details</li>
                </ul>
              </div>
            </div>
          </div>
          <div class="card">
            <div class="card-body">
              <div class="row">
                <div class="col-md-12">
                  <div class="about-info">
                    <h4>About {{product.title}}</h4>
                    <div class="media mt-3">
                        {% if product.image.url %}
                        <img src="{{product.image.url}}" class="mr-3" alt="..." />
                        {% else %}
                        <img src="{% static "img/No_Image_Available.jpg" %}" class="mr-3" alt="..." />
                        {% endif %}
                      <div class="media-body">
                        <ul>
                          <li>
                            <span class="title-span">Name : </span>
                            <span class="info-span">{{product.title}}</span>
                          </li>
                          <li>
                            <span class="title-span">Type : </span>
                            <span class="info-span">{{product.type}}</span>
                          </li>
                          <li>
                            <span class="title-span">Price : </span>
                            <span class="info-span">{{product.price_per_kilo}} DZD/Kg</span>
                          </li>
                          <li>
                            <span class="title-span">Category : </span>
                            <span class="info-span">{{product.category}} </span
                            >
                          </li>
                          <li>
                            <span class="title-span">Gender : </span>
                            <span class="info-span">
                                <form action="{% url 'vendeur:add' product.id %}" method="POST">
                                    {% csrf_token %}
                                <div class='ctrl'>
                                    <div class='ctrl__button ctrl__button--decrement'>&ndash;</div>
                                    <div class='ctrl__counter'>
                                      <input class='ctrl__counter-input' maxlength='10' type='text' value='0' name="quantity">
                                      <div class='ctrl__counter-num'>0</div>
                                    </div>
                                    <div class='ctrl__button ctrl__button--increment'>+</div>
                                  </div>
                                  <button type="submit" class="btn btn-primary">
                                    Ajouter au panier
                                  </button>
                                </form>
                            </span>
                          </li>
                        </ul>
                      </div>
                    </div>
                    <div class="row mt-3">
                      <div class="col-md-12">
                        <p>
                          {{product.desc}}
                        </p>
                      </div>
                    </div>

                  </div>
                </div>
              </div>

            </div>
          </div>



          <script>
            (function() {
              'use strict';
            
              function ctrls() {
                var _this = this;
            
                this.counter = 0;
                this.els = {
                  decrement: document.querySelector('.ctrl__button--decrement'),
                  counter: {
                    container: document.querySelector('.ctrl__counter'),
                    num: document.querySelector('.ctrl__counter-num'),
                    input: document.querySelector('.ctrl__counter-input')
                  },
                  increment: document.querySelector('.ctrl__button--increment')
                };
            
                this.decrement = function() {
                  var counter = _this.getCounter();
                  var nextCounter = (_this.counter > 0) ? --counter : counter;
                  _this.setCounter(nextCounter);
                };
            
                this.increment = function() {
                  var counter = _this.getCounter();
                  var nextCounter = (counter < 9999999999) ? ++counter : counter;
                  _this.setCounter(nextCounter);
                };
            
                this.getCounter = function() {
                  return _this.counter;
                };
            
                this.setCounter = function(nextCounter) {
                  _this.counter = nextCounter;
                };
            
                this.debounce = function(callback) {
                  setTimeout(callback, 100);
                };
            
                this.render = function(hideClassName, visibleClassName) {
                  _this.els.counter.num.classList.add(hideClassName);
            
                  setTimeout(function() {
                    _this.els.counter.num.innerText = _this.getCounter();
                    _this.els.counter.input.value = _this.getCounter();
                    _this.els.counter.num.classList.add(visibleClassName);
                  }, 100);
            
                  setTimeout(function() {
                    _this.els.counter.num.classList.remove(hideClassName);
                    _this.els.counter.num.classList.remove(visibleClassName);
                  }, 200);
                };
            
                this.ready = function() {
                  _this.els.decrement.addEventListener('click', function() {
                    _this.debounce(function() {
                      _this.decrement();
                      _this.render('is-decrement-hide', 'is-decrement-visible');
                    });
                  });
            
                  _this.els.increment.addEventListener('click', function() {
                    _this.debounce(function() {
                      _this.increment();
                      _this.render('is-increment-hide', 'is-increment-visible');
                    });
                  });
            
                  _this.els.counter.input.addEventListener('input', function(e) {
                    var parseValue = parseInt(e.target.value);
                    if (!isNaN(parseValue) && parseValue >= 0) {
                      _this.setCounter(parseValue);
                      _this.render();
                    }
                  });
            
                  _this.els.counter.input.addEventListener('focus', function(e) {
                    _this.els.counter.container.classList.add('is-input');
                  });
            
                  _this.els.counter.input.addEventListener('blur', function(e) {
                    _this.els.counter.container.classList.remove('is-input');
                    _this.render();
                  });
                };
              };
            
              // init
              var controls = new ctrls();
              document.addEventListener('DOMContentLoaded', controls.ready);
            })();
            </script>
          {% endblock content %}

project/templates/vendeur/old_categories.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>home</title>
  
    <link rel="stylesheet" href="{% static 'CSS/products.css' %}">
</head>
<body>

  <div class="container">
      <div class="home">
        <div class="logo">
          <img src="../my photo/LOGOO.jpg" alt="logo" />
        </div>
        <ul>

          <li>
            <a href="{% url 'vendeur:categories' %}" >
              <span class="icon"><i class="fas fa-user-friends"></i></span>
              <span>categories</span>
            </a>
          </li>
          <li>
            <a href="{% url 'vendeur:poubelle' %}" >
              <span class="icon"><i class="fa-solid fa-box"></i></span>
              <span>poubelle</span>
            </a>
          </li>
          <li>
            <a href="{% url 'vendeur:poubelle' %}" >
              <span class="icon"><i class="fa-solid fa-box"></i></span>
              <span>mes commandes</span>
            </a>
          </li>
          <li>
            <a href="{% url 'users:logout' %}">
              <span class="icon"><i class="fa-solid fa-arrow-right-from-bracket"></i></span>
              <span>Logout</span>
            </a>
          </li>
        </ul>
      </div>
    </div>
    <div class="dashboard">
    {% for category in all_categories %}
      
    {% comment %} <aclass="category-card">
      <h3>{{category.title}}</h3>

    </a>
    <a  href="{% url 'vendeur:products' category.slug   %}"  class="product-card">
      <div class="product-image">

      </div>
      <h3>{{product.title}}</h3>
      <div class="product-info">
          <p>Weight: {{product.weight}} kg</p>
          <p>Amount: {{product.price_per_kilo}}</p>
          <p>Price: <br> {{product.price_per_kilo}} DZD/kg</p>
        </div>
        <a href="{% url 'vendeur:products' category.slug   %}" class="details-btn">Details</a>
  </a> {% endcomment %}


  <a href="{% url 'vendeur:products' category.slug   %}" class="product-card">
    <div class="product-image">
      {% if category.banner %}
      <img src="{{category.banner.url}}" alt="{{category.banner.url}}">
      
      {% else %}
      <img src="{% static "img/No_Image_Available.jpg" %}" alt="">
      {% endif %}
    </div>
    <h3>{{category.title}}</h3>


</a>
    
    {% endfor %}
     
      <!-- Add more category cards here -->
    </div> 
  
</body>
</html>

project/templates/vendeur/old_poubelle.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>List of Products</title>
    <link rel="stylesheet" href="{% static 'CSS/poubelle.css' %}">
</head>
<body>
    <div class="contaner">
        <div class="home">
            <div class="logo">
              <img src="../my photo/LOGOO.jpg" alt="logo" />
            </div>
            <ul>
    
              <li>
                <a href="{% url 'vendeur:categories' %}" >
                  <span class="icon"><i class="fas fa-user-friends"></i></span>
                  <span>categories</span>
                </a>
              </li>
              <li>
                <a href="{% url 'vendeur:poubelle' %}" >
                  <span class="icon"><i class="fa-solid fa-box"></i></span>
                  <span>poubelle</span>
                </a>
              </li>
              <li>
                <a href="{% url 'vendeur:poubelle' %}" >
                  <span class="icon"><i class="fa-solid fa-box"></i></span>
                  <span>mes commandes</span>
                </a>
              </li>
              <li>
                <a href="{% url 'users:logout' %}">
                  <span class="icon"><i class="fa-solid fa-arrow-right-from-bracket"></i></span>
                  <span>Logout</span>
                </a>
              </li>
            </ul>
          </div>
    </div>

    <div class="content">
        <h1>List of Products in Cart</h1>
        <table id="productTable">
            <thead>
                <tr>
                    <th>Product ID</th>
                    <th>Product Name</th>
                    <th>DZD / KiloGram</th>
                    <th>Quantity</th>
                    <th>Total</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody id="productTableBody">
                {% for item in poubelle %}
                <tr>
                    <td> {{ item.produit.id }}</td>
                    <td>{{ item.produit.title }}</td>
                    <td>{{ item.produit.price_per_kilo }}</td>
                    <td> 
                        <span>{{ item.quantity }}</span>
                    </td>
                    <td id="price">{{item.price}} DZD</td>
                    <td>
                        <form  action="{% url 'vendeur:delete_from_poubelle' item.id %}" method="POST">
                            {% csrf_token %}
                            <button >Delete</button>
                        </form>
                    </td>
                </tr>
                  
                {% endfor %}
            </tbody>
        </table>
        <div style="text-align: center; margin-top: 20px;">
            <div style="background-color: #f3f3f3; padding: 20px; border-radius: 8px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);">
                <div id="totalPrice" style="margin-bottom: 20px; font-size: 24px; color: #3B8457; font-weight: bold;"></div>
                
                <a href="{% url 'vendeur:sendCommand' %}" style="padding: 12px 24px; background-color: #3B8457; color: #fff; border: none; border-radius: 5px; cursor: pointer; transition: background-color 0.3s ease; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);">Place Order</a>
            
            </div>
        </div>

    </div>
    
    <script>
        // Sample array of products (replace with your actual data)
        price = document.querySelectorAll('#price')
        total = 0
        for (let index = 0; index < price.length; index++) {
            const element = price[index];
            total +=  Number(element.innerHTML.split(' ')[0])
        }
        document.getElementById("totalPrice").innerHTML= "Total : "+total+' DZD'


    </script>
</body>
</html>

project/templates/vendeur/poubelle.html
{% extends "base.html" %}
{% block title %}Categories{% endblock title %}
{% block content %}
<div class="page-header">
  <div class="row align-items-center">
    <div class="col">
      <h3 class="page-title">Pannier</h3>
      <ul class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="">Dashboard</a>
        </li>
        <li class="breadcrumb-item active">Pannier</li>
      </ul>
    </div>
    <div class="col-auto text-right float-right ml-auto">
      <a href="{% url 'vendeur:sendCommand' %}" class="btn btn-outline-primary mr-2">Set commanede</a>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-sm-12">
    <div class="card card-table">
      <div class="card-body">
        <div class="table-responsive">
          <table id="table_id" class="table table-hover table-center mb-0">
            <thead>
              <tr>
                <th> ID</th>
                <th> Name</th>
                <th> DZD / Kg</th>
                <th> Quantity</th>
                <th> total</th>
                <th class="text-right">Action</th>
              </tr>
            </thead>
            <tbody>
              {% for item in poubelle %}
              <tr>
                <td>{{ item.produit.id }}</td>
                <td>
                  <h2>
                    <a>{{ item.produit.title }}</a>
                  </h2>
                </td>
                <td>
                  <h2>
                    <a>{{ item.produit.price_per_kilo }}</a>
                  </h2>
                </td>
                <td>
                  <h2>
                    <a>{{ item.quantity }}</a>
                  </h2>
                </td>
              </td>
              <td id="price">{{item.price}} DZD</td>
              <td>
                <td class="text-center">
                  <div class="actions">
                    <form  action="{% url 'vendeur:delete_from_poubelle' item.id %}" method="POST">
                      {% csrf_token %}
                      <button type="submit" class="btn btn-outline-danger btn-sm">Delete
                        <i class="fas fa-trash"></i>

                      
                    </form>
                  </div>
                </td>
              </tr>
              {% endfor %}

              <tr>
                <td>-----------</td>
                <td>
                  <h2>
                    <a>>-----------</a>
                  </h2>
                </td>
                <td>
                  <h2>
                    <a>>-----------</a>
                  </h2>
                </td>
                <td>
                  <h2>
                    <a>>-----------</a>
                  </h2>
                </td>
              </td>
              <td id="totalPrice">{{item.price}} DZD</td>
              <td>
                <td class="text-center">
                  >-----------
                </td>
              </tr>

            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  // Sample array of products (replace with your actual data)
  price = document.querySelectorAll('#price')
  total = 0
  for (let index = 0; index < price.length; index++) {
      const element = price[index];
      total +=  Number(element.innerHTML.split(' ')[0])
  }
  document.getElementById("totalPrice").innerHTML= "Total : "+total+' DZD'


</script>
{% endblock content %}

project/templates/vendeur/products.html
{% extends "base.html" %}
{% load static %}
{% block title %} categories {% endblock title %} 
{% block content %}
<div class="comp-sec-wrapper">
  <section class="comp-section comp-cards">
    <div class="section-header">
      <h4 class="section-title">Categories</h4>
      <div class="line"></div>
    </div>
    <div class="row">

      {% for product in products %}
      <div class="col-12 col-md-6 col-lg-4 d-flex">
        <div class="card flex-fill">
          {% if product.image %}
          <img alt="Card Image" src="{{product.image.url}}" class="card-img-top">
          {% else %}
          <img alt="Card Image" src="{% static 'img/No_Image_Available.jpg' %}" class="card-img-top">
          {% endif %}
        <div class="card-header">
        <h5 class="card-title mb-0">{{product.title}}</h5>
        </div>
        <ul class="list-group list-group-flush">
         <li class="list-group-item">Weight : {{product.weight}} kg</li>
        <li class="list-group-item">Amount : {{product.price_per_kilo}}</li>
        <li class="list-group-item">Price : {{product.price_per_kilo}} DZD/kg</li>
        </ul>
        <div style="text-align: center;" class="card-body">
          
          <a class="btn btn-primary" href="{% url 'vendeur:details' product.id %}">details</a>
        </div>
        </div>
      </div>
      
      {% endfor %}
    </div>
    </div>
  </section>
</div>
{% endblock content %}